### ISSUE TITLE
Clean up and get committed to base

### ISSUE THREAD

**Issue by johalun** [cwithmichael/dragon_rise_driver#2]
Hi

Thanks for doing this work! With this I can now play Amiga games using fs-uae and my (different vendor) snes controller :) 

I'd like to clean this up a bit, maybe add evdev support if it makes sense and get committed to base. Did you do anymore work or is this the latest version?

**Comment by cwithmichael** [comment]
Hey thanks! I'm glad to hear that it was helpful for you. This is the latest version. I haven't touched it in a long time. Please feel free to make any changes you think can improve it.

**Comment by johalun** [comment]
https://reviews.freebsd.org/D15385

**Comment by cwithmichael** [comment]
Thanks!
